SELECT CARRINHOS.COD_CARRINHO,
		USUARIOS.USUARIO,
		CARRINHOS.FINALIZADO,
        ITENS.PRODUTO,
        ITENS_CARRINHO.QUANTIDADE,
        ITENS.PRECO,
        ITENS.IMAGEM

FROM CARRINHOS
INNER JOIN itens_carrinhos ON carrinhos.COD_CARRINHO = itens_carrinhos.COD_CARRINHO
INNER JOIN ITENS ON ITENS.CODIGO = itens_carrinhos.COD_PRODUTO
WHERE USUARIOS.USUARIO = "aleatorio";