CREATE DATABASE IF NOT EXISTS Produtos;
USE Produtos;

CREATE TABLE IF NOT EXISTS Produtos(
    CODIGO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PRODUTO VARCHAR(50),
    DESCRICAO VARCHAR(200),
    DESTAQUE BOOL,
    PRECO FLOAT,
    FOTO VARCHAR(270),
    DISPONIBILIDADE BOOL
);

CREATE TABLE IF NOT EXISTS Usuarios(
    USUARIO VARCHAR(20) PRIMARY KEY, 
    SENHA VARCHAR(200) NOT NULL,
    NOME VARCHAR(100) DEFAULT "ANONIMO"
);

CREATE TABLE IF NOT EXISTS Carrinhos(
    COD_CARRINHO INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO VARCHAR(20),
    DATA DATETIME DEFAULT CURRENT_TIMESTAMP,
    FINALIZADO BOOL,
    CONSTRAINT FK_CARRINHO_USUARIO 
        FOREIGN KEY (USUARIO) REFERENCES Usuarios(USUARIO)
);

CREATE TABLE IF NOT EXISTS Itens_carrinhos(
    COD_ITENS_CARRINHOS INT AUTO_INCREMENT PRIMARY KEY,
    COD_CARRINHO INT,
    COD_PRODUTO INT,
    QUANTIDADE INT DEFAULT 1,
    CONSTRAINT FK_ITENSCARRINHO_CARRINHOS 
        FOREIGN KEY (COD_CARRINHO) REFERENCES Carrinhos (COD_CARRINHO),
    CONSTRAINT FK_ITENSCARRINHO_PRODUTO 
        FOREIGN KEY (COD_PRODUTO) REFERENCES Produtos (CODIGO)
);

