CREATE DATABASE IF NOT EXISTS Produtos;
USE Produtos;

CREATE TABLE IF NOT EXISTS Produtos(
CODIGO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
PRODUTO VARCHAR(50),
DESCRICAO VARCHAR(200),
DESTAQUE BOOL,
PRECO FLOAT,
FOTO VARCHAR(270),
DISPONIBILIDADE BOOL
)