CREATE DATABASE IF NOT EXISTS Produtos;
USE Produtos;

CREATE TABLE IF NOT EXISTS Produtos(
CODIGO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
PRODUTO VARCHAR(50),
DESCRICAO VARCHAR(200),
DESTAQUE BOOL,
PRECO FLOAT,
FOTO VARCHAR(270),
DISPONIBILIDADE BOOL
);

CREATE TABLE IF NOT EXISTS Usuarios(
    USUARIO VARCHAR(20) PRIMARY KEY, 
    SENHA VARCHAR (200) NOT NULL,
    NOME VARCHAR(100) DEFAULT "ANONIMO"
);